# Site settings
title: Cooking with Rebecca
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My Cooking Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cooking-with-rebecca.github.io" # the base hostname & protocol for your site
# github_username: jekyll
# twitter_username: jekyll

# Build settings
markdown: kramdown
